wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: PGNet
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706267765.429628
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.2
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
